spring:
  application:
    name: casestudy
  profiles:
    default: local-inmemory
  jackson:
    time-zone: Asia/Kolkata

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: local-inmemory
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
casestudy:
  storage: in-memory
management:
  health:
    db:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/quince?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET time_zone = '+05:30'
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata
    show-sql: false
casestudy:
  storage: mysql
management:
  health:
    db:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: mysql-redis
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/quince?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET time_zone = '+05:30'
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata
    show-sql: false
casestudy:
  storage: mysql-redis
management:
  health:
    db:
      enabled: true
